# 자, 이전 실습을 통해서 우리는 NN을 만들어봤습니다.
## 우리가 만들 network는 3-layer Feed forward Fully Connected Neural Network입니다.

- <span style = 'font-size:1.2em;line-height:1.5em'><b>input layer:</b> 784 neurons(MNIST 데이터는 28*28 pixel로 되어있고, 이를 쭉 펼치면 784차원이 됩니다.)</span>
- <span style = 'font-size:1.2em;line-height:1.5em'><b>1st hidden layer:</b> 50 neurons</span>
- <span style = 'font-size:1.2em;line-height:1.5em'><b>2nd hidden layer:</b> 100 neurons</span>
- <span style = 'font-size:1.2em;line-height:1.5em'><b>output layer:</b> 10 neurons (0~9까지의 숫자가 있기 때문에, 총 10개의 클래스)</span>

- <span style = 'font-size:1.2em;line-height:1.5em'>Lecture03_2의 training neural network에서 mini-batch단위로 학습을 한다는 건 말씀을 드렸습니다.</span>
- <span style = 'font-size:1.2em;line-height:1.5em'>근데, 학습 뿐만 아니라 실제 결과를 산출하는 inference과정에서도 mini-batch단위로 수행 합니다.</span>
- <span style = 'font-size:1.2em;line-height:1.5em'>둘다 forward propagation이 사용되는데요. <b>즉, forward propagation은 mini-batch단위로 수행한다고 보셔도 되겠습니다.</b></span>

## Mini-batch단위로 수행하는 forward propagation을 구현해 보겠습니다.

## 미리 학습해둔 weight를 불러오겠습니다.
- <span style = 'font-size:1.2em;line-height:1.5em'>미리 학습한 weight파일은 sample_weights 폴더안에 sample_weight.pkl이라는 파일로 저장되어 있습니다.</span>
- <span style = 'font-size:1.1em;line-height:1.3em'>(출처: https://github.com/WegraLee/deep-learning-from-scratch)</span>


In [11]:
import numpy as np
import pickle

In [12]:
import pickle
# pkl확장자의 파일은 다음과 같은 방식으로 열 수 있습니다!
with open("sample_weights/sample_weight.pkl","rb") as f:
    network = pickle.load(f)

In [13]:
# sample_weight라는 파일에는 dictionary가 저장되어 있네요!
type(network)

dict

In [14]:
# dictionary에 뭐가 들어있는지 볼까요?
for key, value in network.items():
    print(f"{key}'s shape: {value.shape}, type: {type(value)}")

b2's shape: (100,), type: <class 'numpy.ndarray'>
W1's shape: (784, 50), type: <class 'numpy.ndarray'>
b1's shape: (50,), type: <class 'numpy.ndarray'>
W2's shape: (50, 100), type: <class 'numpy.ndarray'>
W3's shape: (100, 10), type: <class 'numpy.ndarray'>
b3's shape: (10,), type: <class 'numpy.ndarray'>


## 이제 MNIST 데이터를 mini-batch (size=100)단위로 forward propagation해보겠습니다.

In [15]:
# mnist.py에서 우리가 실제로 사용할 load_mnist함수만 불러올게요
from mnist import load_mnist

In [16]:
(x_trn, y_trn), (x_tst, y_tst) = load_mnist(flatten=True, normalize=False)

In [17]:
batch_size = 100

In [18]:
idxs=np.arange(0,batch_size).tolist()

In [19]:
x_sample = x_trn[idxs]
y_sample = y_trn[idxs]

In [20]:
from act_func import *

In [21]:
W1, W2, W3 = network['W1'], network['W2'], network['W3']
b1, b2, b3 = network['b1'], network['b2'], network['b3']

a1 = np.dot(x_sample, W1)+b1
z1 = sigmoid(a1)
a2 = np.dot(z1, W2)+b2
z2 = sigmoid(a2)
a3 = np.dot(z2,W3)+b3
a3 = softmax(a3)

/Users/jimin/Library/CloudStorage/GoogleDrive-shwlals96@gmail.com/내 드라이브/KMU/4학년 1학기/딥러닝/과제/deeplearning/[Lab]Week03/act_func.py:27: RuntimeWarning: overflow encountered in exp
  result = 1/(1+np.exp(-x))


## 0~99번째 데이터에 대해서 NN의 output값은 다음과 같습니다.

In [22]:
print(a3.shape)

(100, 10)


In [23]:
a3

array([[1.65985307e-06, 2.98940250e-08, 1.58116684e-08, 8.26428077e-05,
        6.45307086e-10, 1.36453204e-03, 1.15899557e-09, 3.38990105e-07,
        9.73324518e-07, 2.72353986e-07],
       [3.40686329e-02, 1.84032772e-11, 2.71697036e-06, 2.74623375e-07,
        3.58174335e-09, 1.35710479e-05, 4.45646378e-07, 1.39735988e-07,
        2.49776555e-08, 2.49725112e-08],
       [9.72917036e-09, 7.25479143e-09, 1.11345753e-05, 3.62529136e-07,
        1.67023492e-04, 6.68745592e-09, 1.30921194e-06, 1.36441486e-07,
        6.24422611e-08, 3.49156608e-07],
       [1.32899323e-12, 1.32452082e-02, 1.79460858e-05, 3.40645033e-06,
        5.17059640e-08, 6.73735201e-08, 1.12443892e-07, 1.12232946e-07,
        6.26141264e-06, 8.10825362e-09],
       [2.05327769e-10, 5.56672681e-08, 5.01078290e-08, 3.03691479e-07,
        1.82125696e-05, 2.04738644e-08, 1.64209513e-09, 1.67042276e-06,
        8.47152205e-06, 4.42205369e-03],
       [1.23826089e-06, 1.71496028e-09, 5.15718712e-04, 2.09475797e-06,
   

## softmax값이 최대인 class로 분류합니다. NN은 어느 class로 분류했을까요?

In [14]:
np.argmax(a3, axis=1)

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 3, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 3, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 2, 7, 1, 6, 3, 0, 2, 1, 1, 7, 8, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1])

## 실제값과 비교하면 어떨까요?

In [15]:
print(y_sample[idxs])

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 6 9 0 5 6
 0 7 6 1 8 7 9 3 9 8 5 9 3 3 0 7 4 9 8 0 9 4 1 4 4 6 0 4 5 6 1 0 0 1 7 1 6
 3 0 2 1 1 7 9 0 2 6 7 8 3 9 0 4 6 7 4 6 8 0 7 8 3 1]


## 자, 그럼 이제 60000개의 데이터에 대해서 NN의 모든 output을 계산해보죠

In [16]:
result = []
for i in range(0,x_trn.shape[0],batch_size):
    start_idx = i
    end_idx = i+batch_size
    x_sample = x_trn[start_idx:end_idx]
    a1 = np.dot(x_sample, W1)+b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2)+b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3)+b3
    a3 = softmax(a3)
    
    result.extend(np.argmax(a3, axis=1))
result = np.array(result)

In [17]:
result

array([5, 0, 4, ..., 5, 6, 8])

## 정확도는 얼마나 될까요?

In [18]:
np.sum(result == y_trn)

55511

In [19]:
print(f'미리 학습한 모델의 정확도는 {100*np.sum(result==y_trn) / len(y_trn):.2f}%입니다.')

미리 학습한 모델의 정확도는 92.52%입니다.


# mini_batch로 계산하는게 single data단위로 계산하는 것보다 빠릅니다
## 시간을 비교해볼까요?

### single data단위

In [20]:
%%time

result1 = []
for i in range(x_trn.shape[0]):
    x_sample = x_trn[i]
    a1 = np.dot(x_sample, W1)+b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2)+b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3)+b3
    a3 = softmax(a3)
    
    result1.append(np.argmax(a3))
result1 = np.array(result1)

CPU times: user 12.4 s, sys: 6.88 s, total: 19.3 s
Wall time: 4.5 s


In [21]:
%%time

result2 = []
for i in range(0,x_trn.shape[0],batch_size):
    start_idx = i
    end_idx = i+batch_size
    x_sample = x_trn[start_idx:end_idx]
    a1 = np.dot(x_sample, W1)+b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2)+b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3)+b3
    a3 = softmax(a3)
    
    result2.extend(np.argmax(a3, axis=1))
result2 = np.array(result2)

CPU times: user 2.58 s, sys: 609 ms, total: 3.19 s
Wall time: 438 ms


In [22]:
print(result1)
print(result2)
print(np.sum(result1==result2))

[5 0 4 ... 5 6 8]
[5 0 4 ... 5 6 8]
60000
